"""Advisor payload contract shared by UI payload builders and tests."""

from __future__ import annotations


ADVISOR_PAYLOAD_MODE = "ui-selected-pokemon-v0.18"

ADVICE_ITEM_CONTEXT_KEYS = frozenset(
    {
        "survival_context",
        "recovery_context",
        "accuracy_context",
        "critical_context",
        "flinch_context",
        "multi_hit_context",
        "type_boost_context",
        "species_stat_item_context",
        "speed_order_context",
        "resist_berry_context",
        "chilan_berry_context",
        "charge_context",
    }
)

ADVICE_CONTEXT_KEYS = frozenset({*ADVICE_ITEM_CONTEXT_KEYS, "speed_context"})

ADVICE_CONTEXT_SIDE_FIELDS = ("attacker_side", "defender_side")

ADVICE_CONTEXTS_REQUIRING_MOVE_LOCAL_ITEM_EFFECT_SCRUB = frozenset(
    {
        "type_boost_context",
        "species_stat_item_context",
    }
)

DEBUG_ONLY_REASON_PHRASES = (
    "effect is not applied",
    "item effect is not included",
    "not modeled",
    "not reflected",
    "unsupported",
    "deferred",
    "blocked",
)

ADVISOR_KNOWN_LIMITATIONS = [
    "Only user-selected moves and explicitly labeled opponent move data are included in the payload.",
    "Empty move slots are omitted.",
    "Move damage estimates, when present, use default assumptions and are not final battle damage.",
    "Every damage estimate includes an assumption_profile that identifies the stat model used.",
    "User-confirmed final stats may be used when stat_profiles provides all six stats.",
    "item_profiles distinguishes unknown, none, system_default_none, and user_confirmed item state.",
    "v0.23 item UI uses Champions legal item repository options for normal selection.",
    "Damage-supported but non-legal/debug items are not normal item selector options.",
    "Legal items and modeled item effects are separate concepts.",
    "Legal-but-not-modeled items may be user-confirmed, but their effects are not applied unless item_effects marks them applied.",
    "Opponent item defaults to unknown unless T1 confirms no item or selects an item.",
    "system_default_none means damage was calculated with a no-item assumption.",
    "When available=true item contexts are present in the default advice payload, the prompt must require the LLM to mention each listed available item context at least once when directly relevant.",
    "When available=true item contexts are present, do not describe those available item effects as unavailable, unmodeled, not included, not reflected, no item is considered, assuming no item, without item effects, or default no-item assumption.",
    "Available item context wording must remain limited and must not become final KO odds, guaranteed survival, guaranteed move order, exact final stats, or final battle truth.",
    "speed_context, when present, is raw/effective Speed comparison only and is not final turn order.",
    "Raw/effective Speed comparison is available only when both active Pokemon have user-confirmed final Speed in v0.30.",
    "Default Speed fallback is not used in v0.30.",
    "Do not say a Pokemon will move first when speed_context.is_final_turn_order is false.",
    "Use wording such as based on raw Speed only or appears faster by raw Speed for speed_context comparisons.",
    "effective_speed, when present, is a supported speed modifier estimate and is not final turn order.",
    "Choice Scarf speed may be applied in speed_context only when the item is user-confirmed.",
    "Choice lock remains not modeled when a user-confirmed Choice item is applied.",
    "Quick Claw speed-order context may appear only as limited speed_order_context.",
    "speed_order_context applies only when Quick Claw is user-confirmed and Champions legal.",
    "speed_order_context may say Quick Claw may affect move order, but final move order is not calculated.",
    "Quick Claw activation probability is not calculated in speed_order_context.",
    "speed_order_context does not calculate speed ties, priority, Trick Room, Tailwind, paralysis, boosts, abilities, weather, item consumption, or turn sequencing.",
    "Do not say will move first, guaranteed outspeeds, confirmed first, always acts before, wins the speed interaction, or safe because it moves first from speed_order_context.",
    "If speed_order_context is unavailable, treat the reason as developer/debug/contract metadata only.",
    "Choice Scarf is not modeled through speed_order_context; keep Choice Scarf in speed_context.",
    "If raw_speed and effective_speed disagree, explain the difference without guaranteeing action order.",
    "Only item effects marked as applied in damage_estimate.item_effects are included in damage numbers.",
    "User-facing modeled item contexts require Champions legal item coverage from data/static/champions_legal_items.json.",
    "items.json and items_damage.json are item/effect metadata, not Champions legal coverage sources.",
    "If a user-confirmed item is absent from the Champions legal item fixture, do not emit modeled item context; use blocked_by_legal_item_coverage.",
    "Blocked or future-only item reasons are developer/debug/contract metadata, not normal user-facing advice content.",
    "Do not include blocked or future-only item effects in user-facing recommendation text unless the user explicitly asks about that item.",
    "In default advice, do not mention blocked item names, do not say user-confirmed Loaded Dice, and do not say Power Herb when those items are blocked by legal coverage.",
    "Do not say Loaded Dice is not modeled or Power Herb is not modeled by default when those items are blocked by legal coverage.",
    "Do not say a blocked item effect is not included by default; keep blocked item explanations out of normal advice.",
    "Do not use generic blocked item substitutes such as the user-confirmed item effect, held item effect, selected item effect, or item-based limitation in default advice.",
    "Do not mention that a blocked item exists by saying its effect is absent, ignored, unavailable, excluded, unsupported, or outside the estimate.",
    "If the user explicitly asks about a blocked item, explain only that Champions legal coverage is not confirmed, so the item effect is not reflected in advice.",
    "Do not imply blocked or future-only items are available in Champions.",
    "For unavailable, deferred, blocked, unconfirmed, non-triggered, or absent item contexts, treat the reason as developer/debug/contract metadata by default.",
    "Do not say item effect is not included, opponent's item effect is not included, or user-confirmed item effect is not included for unavailable item contexts in default advice.",
    "Do not say item is not modeled, item effect is not applied, not included in this estimate, or not reflected in the calculation for unavailable item contexts in default advice.",
    "Do not mention unavailable or deferred item names or effects unless the user explicitly asks about that item.",
    "When item_effects.attacker_item.status is applied, mention that the supported item damage modifier is applied.",
    "Type boosting item damage is included only when item_effects.attacker_item.status is applied.",
    "Do not say a type boosting item boosted damage when the move type does not match or the item is unsupported.",
    "Legal item selection does not imply the selected item has a modeled effect.",
    "Fairy Feather is legal but not damage-modeled until a catalog-backed modifier exists.",
    "Type-boost item context may appear only as limited type_boost_context.",
    "type_boost_context applies only to user-confirmed, Champions legal, damage-supported type-boosting items when move type matches boosted type.",
    "type_boost_context does not change raw damage_range or rolls beyond the existing damage_estimate.item_effects calculation.",
    "ko_context is unchanged by type_boost_context.",
    "Type-boost-adjusted KO/OHKO/2HKO context is not calculated.",
    "If type_boost_context is unavailable, treat the reason as developer/debug/contract metadata only.",
    "Do not say boosted damage guarantees KO, secures the KO, proves the KO, or is final battle damage.",
    "Light Ball species-stat item context may appear only as limited species_stat_item_context.",
    "species_stat_item_context applies only to user-confirmed, Champions legal Light Ball on Pikachu when local species-stat metadata exists.",
    "species_stat_item_context is a sibling explanation of an applied Light Ball modifier in damage_estimate.item_effects.",
    "Eligible Pikachu Light Ball damage estimates use default stat assumptions plus the supported Light Ball species-stat modifier.",
    "Eligible Pikachu Light Ball raw damage rolls and ko_context are based on the adjusted damage estimate rolls.",
    "species_stat_item_context does not infer exact EV/IV/nature-adjusted final stats and does not create final KO truth.",
    "damage_estimate.item_effects remains the source of truth for whether a supported item modifier was applied to a specific estimate.",
    "If species_stat_item_context is unavailable, treat the reason as developer/debug/contract metadata only.",
    "Do not mention non-Pikachu Light Ball mismatch, unsupported reason, missing metadata, or not modeled wording in default advice.",
    "When species_stat_item_context is available, say Light Ball is a Pikachu-specific offensive item context applied in the damage estimate when damage_estimate.item_effects marks the supported modifier as applied.",
    "Do not say Light Ball is not included or Light Ball is not modeled when species_stat_item_context is available.",
    "When species_stat_item_context is available, do not use generic no-item/default-assumption wording such as no item effects, without item effects, assuming no item, default no-item assumption, item not included, item not modeled, or item not reflected.",
    "When species_stat_item_context is available and item_effects marks the supported modifier as applied, describe the damage estimate as default assumptions plus the supported Light Ball modifier.",
    "When species_stat_item_context is available, say the context is not final stat truth and not a final KO guarantee.",
    "Do not say guaranteed KO, always doubles damage, confirmed OHKO because of Light Ball, all Electric-type Pokemon benefit from Light Ball, Light Ball works on any holder, final stats are fully known, or exact EV/IV/nature-adjusted stats are known.",
    "If an item damage modifier is applied, describe the estimate as default assumptions plus the supported item modifier, not only default assumptions.",
    "If Life Orb is applied, say Life Orb recoil is not modeled.",
    "If Choice Scarf, Choice Band, or Choice Specs is applied, say choice lock is not modeled.",
    "Do not mention choice lock for non-Choice items such as Charcoal, Mystic Water, Black Belt, Metal Coat, Sharp Beak, Fairy Feather, Leftovers, Focus Sash, or Focus Band.",
    "Type matchup descriptions must use damage_estimate.type_effectiveness when present.",
    "Do not call a move super effective, resisted, or immune unless type_effectiveness explicitly supports it.",
    "Do not print raw type_effectiveness labels like super_effective or not_very_effective; convert them to natural wording.",
    "Life Orb recoil is not connected.",
    "Sitrus Berry and Leftovers recovery may appear only as limited recovery_context.",
    "recovery_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by recovery_context and KO/OHKO/2HKO estimates do not include recovery.",
    "recovery_context applies only when Sitrus Berry or Leftovers is user-confirmed and defender max HP is available.",
    "Sitrus Berry recovery_context is threshold recovery limited context; exact activation timing and item consumption are not tracked.",
    "Leftovers recovery_context is end-of-turn limited context; exact turn sequencing is not modeled.",
    "When recovery_context is available, keep recovery wording concise and say exact activation timing, item consumption, and turn sequencing are not modeled.",
    "Say recovery may affect follow-up KO/2HKO only under limited assumptions.",
    "Do not claim final 2HKO or 3HKO truth from recovery_context without Turn Engine.",
    "Do not infer Sitrus Berry or Leftovers recovery if the item is unknown or unconfirmed.",
    "Do not say Sitrus Berry definitely activates, KO chance includes recovery, or recovery changes the damage range.",
    "Bright Powder accuracy may appear only as limited accuracy_context.",
    "accuracy_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by accuracy_context and KO/OHKO/2HKO estimates do not include hit chance.",
    "accuracy_context applies only when Bright Powder is user-confirmed and move accuracy metadata is available.",
    "Bright Powder may reduce hit reliability, but it is not damage reduction.",
    "When accuracy_context is available, keep accuracy wording concise and mention that raw damage and KO/OHKO/2HKO estimates do not include hit chance.",
    "When accuracy_context is available, include one concise limitation sentence that final hit probability, accuracy/evasion stages, ability/weather interactions, multi-hit accuracy, and turn sequencing are not modeled.",
    "Hit-adjusted KO probability is not calculated in accuracy_context.",
    "Final hit probability is not calculated in accuracy_context.",
    "Do not claim the move will miss or that a miss is guaranteed from accuracy_context.",
    "Do not say the hit-adjusted KO chance is a percent unless an explicit future field calculates it.",
    "Do not infer Bright Powder accuracy effects if the item is unknown or unconfirmed.",
    "Accuracy/evasion stages, ability interactions, weather, multi-hit accuracy, and turn sequencing are not modeled for accuracy_context.",
    "Scope Lens critical-hit context may appear only as limited critical_context.",
    "critical_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by critical_context and KO/OHKO/2HKO estimates do not include crit chance.",
    "critical_context applies only when Scope Lens is user-confirmed.",
    "Scope Lens may increase critical-hit likelihood, but it is not a direct damage boost.",
    "When critical_context is available, keep critical-hit wording concise and mention that raw damage and KO/OHKO/2HKO estimates do not include crit chance.",
    "Final critical-hit probability is not calculated in critical_context.",
    "Crit-adjusted KO probability is not calculated in critical_context.",
    "Do not claim the move will crit or that a critical hit is guaranteed from critical_context.",
    "Do not infer Scope Lens critical-hit effects if the item is unknown or unconfirmed.",
    "Critical-hit stages, abilities, move-specific crit effects, and turn sequencing are not modeled for critical_context.",
    "King's Rock flinch context may appear only as limited flinch_context.",
    "flinch_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by flinch_context and KO/OHKO/2HKO estimates do not include flinch chance.",
    "flinch_context applies only when King's Rock is user-confirmed.",
    "King's Rock may add flinch pressure, but it is not a direct damage boost.",
    "When flinch_context is available, say the raw damage estimate is unchanged and raw ko_context is unchanged.",
    "When flinch_context is available, avoid wording like damage modifier is not included; prefer raw damage estimate is unchanged.",
    "When flinch_context is available, keep flinch wording concise and mention that raw damage and KO/OHKO/2HKO estimates do not include flinch chance.",
    "When flinch_context is available, include one concise limitation sentence that speed order, target action state, abilities, multi-hit handling, and turn sequencing are not modeled.",
    "Final flinch probability is not calculated in flinch_context.",
    "Flinch-adjusted turn or outcome probability is not calculated in flinch_context.",
    "Do not claim the target will flinch, cannot move, or that flinch is guaranteed from flinch_context.",
    "Do not infer King's Rock flinch effects if the item is unknown or unconfirmed.",
    "Speed order, target action state, abilities, multi-hit handling, and turn sequencing are not modeled for flinch_context.",
    "Loaded Dice multi-hit context is blocked/future-only until Loaded Dice legal coverage is confirmed.",
    "Power Herb remains blocked; charge_moves.json is move metadata and does not establish Power Herb legality.",
    "multi_hit_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by multi_hit_context and KO/OHKO/2HKO estimates do not include multi-hit count changes.",
    "multi_hit_context applies only when Loaded Dice is user-confirmed, legal coverage is confirmed, and move multi-hit metadata is available.",
    "Loaded Dice may improve multi-hit reliability for eligible moves, but it is not a direct damage boost.",
    "When multi_hit_context is available, keep multi-hit wording concise and mention that raw damage and KO/OHKO/2HKO estimates do not include multi-hit count changes.",
    "Final hit count probability is not calculated in multi_hit_context.",
    "Multi-hit-adjusted KO probability is not calculated in multi_hit_context.",
    "Do not claim a specific number of hits will occur or that 5 hits are guaranteed from multi_hit_context.",
    "Do not claim Loaded Dice breaks Focus Sash unless that interaction is explicitly modeled.",
    "Do not infer Loaded Dice multi-hit effects if the item is unknown or unconfirmed.",
    "Focus Sash, King's Rock, accuracy, crit per-hit handling, and turn sequencing are not modeled for multi_hit_context.",
    "Type-resist berry context may appear only as limited resist_berry_context.",
    "resist_berry_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by resist_berry_context and KO/OHKO/2HKO estimates do not include berry reduction.",
    "When resist_berry_context is available, explicitly say the raw damage estimate is unchanged and raw ko_context is unchanged.",
    "resist_berry_context applies only when a standard type-resist berry is user-confirmed, legal coverage is confirmed, incoming move type is known, and the move is super-effective.",
    "Resist berry edge cases require explicit support before advice can use them.",
    "A type-resist berry may reduce a qualifying super-effective hit, but berry-adjusted damage is not calculated.",
    "Berry-adjusted KO probability is not calculated in resist_berry_context.",
    "Item consumption is not tracked in resist_berry_context.",
    "Do not say the Pokemon definitely survives from resist_berry_context.",
    "Do not infer resist berry effects if the item is unknown or unconfirmed.",
    "If resist_berry_context is unavailable, treat the unavailable reason as developer/debug/contract metadata only.",
    "Do not mention unavailable resist berry names, berry effects, or unavailable reasons in default advice.",
    "Do not say Yache Berry effect is not applied, the berry effect is not included, or the berry is not modeled in default advice unless the user explicitly asks about that berry.",
    "Ability, weather, Tera, multi-hit handling, item consumption, and turn sequencing are not modeled for resist_berry_context.",
    "Chilan Berry context may appear only as limited chilan_berry_context.",
    "chilan_berry_context applies only when Chilan Berry is user-confirmed, legal coverage is confirmed, local metadata marks always_resist true for Normal, incoming move type is Normal, and the move is damaging.",
    "chilan_berry_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by chilan_berry_context and KO/OHKO/2HKO estimates do not include Chilan Berry reduction.",
    "Chilan-adjusted damage and Chilan-adjusted KO probability are not calculated in chilan_berry_context.",
    "Item consumption is not tracked in chilan_berry_context.",
    "When chilan_berry_context is available, say Chilan Berry is a Normal-type limited context and may reduce damage from a Normal-type damaging move.",
    "When chilan_berry_context is available, say raw damage rolls and ko_context remain based on the current calculator and the context is not integrated into final KO odds.",
    "Do not say Chilan Berry is not included or Chilan Berry is not modeled when chilan_berry_context is available.",
    "Do not say guaranteed survival, confirmed live, will survive because of Chilan Berry, KO chance is reduced to a value, final damage is halved, raw damage rolls already include Chilan Berry, or Chilan Berry applies to all move types.",
    "If chilan_berry_context is unavailable, treat the unavailable reason as developer/debug/contract metadata only.",
    "Do not mention unavailable Chilan Berry names, effects, or unavailable reasons in default advice.",
    "Focus Sash and Focus Band survival may appear only as limited survival_context, not as damage reduction.",
    "survival_context does not change raw damage_range or rolls.",
    "ko_context is unchanged by survival_context and KO/OHKO/2HKO estimates do not include Focus Band activation.",
    "Focus Sash survival_context applies only when Focus Sash is user-confirmed and HP is full.",
    "When Focus Sash survival_context is available, say may survive at 1 HP; do not say will survive, definitely survives, or guarantees survival.",
    "Focus Band survival_context applies only when Focus Band is user-confirmed, Champions legal, and raw incoming damage is potentially lethal.",
    "When Focus Band survival_context is available, say may occasionally survive and survival is not guaranteed.",
    "Do not say Focus Band will survive, guaranteed survive, cannot be KO'd, confirmed survival, safe to take the hit, or survives this hit.",
    "Focus Band activation probability and final survival probability are not calculated.",
    "When survival_context is available, include one concise limitation sentence that multi-hit moves, hazards, chip damage, item consumption, activation probability, and exact turn sequencing are not modeled.",
    "Multi-hit moves, hazards, residual damage, weather/status chip, ability interactions, and exact turn sequencing are not modeled for survival_context.",
    "Do not infer Focus Sash or Focus Band if the item is unknown or unconfirmed.",
    "ko_context, when present, is limited damage-roll context only and is not final battle truth.",
    "ko_context does not change raw damage_range or rolls.",
    "OHKO chance in ko_context is based on damage rolls only.",
    "2HKO context uses limited min/max assumptions and is not final turn simulation.",
    "ko_context does not model accuracy, speed order, priority, recovery, hazards, chip damage, switching, protection, or turn sequencing.",
    "survival_context is separate from raw ko_context and is not included in KO probability.",
    "Do not infer damage, OHKO/2HKO, or KO chance unless explicit calculated fields are provided.",
    "Known opponent moves are user-confirmed only.",
    "Opponent candidate moves are possible Champions moves, not confirmed moves.",
    "Do not assume the opponent has a candidate move unless it appears in known_moves.",
    "Candidate moves may be mentioned as possible threats only when labeled as unconfirmed.",
    "Opponent known move damage estimates, when present, are default-assumption reference values only.",
    "Opponent candidate move damage is not calculated in v0.18.",
    "opponent_assumptions, when present, contains possible opponent profiles, not confirmed sets.",
    "opponent_assumptions mode is a historical behavior label; schema_version and metadata_version describe the current payload shape.",
    "Opponent assumptions version fields are developer/contract metadata and should not be mentioned in user-facing battle advice.",
    "opponent_assumptions.calculation_usage context_only means samples are not used directly for damage or speed calculations.",
    "When opponent_assumptions.available is true and possible_samples exist, briefly mention that possible sample context exists when relevant.",
    "When possible sample context is mentioned, keep it to at most one short limitation sentence.",
    "Do not dump sample_id, full stats, source metadata, update_policy, coverage_probability, or full Top-K sample lists into the response.",
    "When opponent_assumptions.available is false, do not invent samples or force a sample limitation.",
    "Opponent sample role, archetype_id, and possible_items are context-only metadata, not confirmed opponent information.",
    "Opponent sample possible_items are possible assumptions, not confirmed held items.",
    "Do not enumerate opponent sample metadata by default; keep sample visibility concise.",
    "Do not describe sample_assumed opponent samples as user-confirmed information.",
    "Do not interpret prior_probability null as zero probability.",
    "Do not claim Top-K omitted opponent sample archetypes are impossible.",
    "Do not infer final turn order, KO, survival, or exact stats from possible opponent samples.",
    "Priority, Tailwind, Trick Room, paralysis, Speed stages, selected ability speed effects, final action order, and Turn Engine state remain unknown.",
    "Use my_available_moves damage_estimates to compare the user's own move options.",
    "Base stats are species reference data, not EVs or final calculated battle stats.",
    "EV/IV/nature/boosts/weather/terrain/exact HP are not connected in v0.16.",
    "Do not infer EV/IV/nature/item from user-confirmed final stats.",
    "Terastallization is banned in PoChamps and must not be considered.",
    "Do not assume unprovided EVs, IVs, nature, held items, boosts, weather, terrain, exact HP, move sets, or Tera types.",
    "Speed tier, OHKO/2HKO, KO chance, and survival claims are uncertain unless explicit calculated fields are provided.",
    "Recommendation is based on selected Pokemon identity and available UI state only.",
]

ADVISOR_DAMAGE_ASSUMPTIONS = {
    "level": 50,
    "ivs": "31 all",
    "evs": "0 all",
    "nature": "neutral",
    "item": "none",
    "boosts": "none",
    "weather": "none",
    "terrain": "none",
    "screens": "none",
    "critical": False,
    "doubles": False,
    "ability_effects": "not_applied_unselected",
}

ADVISOR_DEFAULT_ASSUMPTION_PROFILE = {
    "id": "default_level50_ivs31_evs0_neutral_no_item",
    "label": "Default Level 50 / IV 31 / EV 0 / neutral nature / no item",
    "source": "system_default",
    "confidence": "rough_reference",
    "is_user_confirmed": False,
}

ADVISOR_USER_CONFIRMED_FINAL_STATS_PROFILE = {
    "id": "user_confirmed_final_stats_level50",
    "label": "User-confirmed final stats / Level 50",
    "source": "user_input",
    "confidence": "higher_confidence_reference",
    "is_user_confirmed": True,
}

ADVISOR_DEFAULT_WITH_DAMAGE_ITEM_PROFILE = {
    "id": "default_level50_ivs31_evs0_neutral_with_damage_item",
    "label": "Default Level 50 / IV 31 / EV 0 / neutral nature / supported damage item",
    "source": "system_default_and_user_input",
    "confidence": "rough_reference_with_user_confirmed_item",
    "is_user_confirmed": False,
}

ADVISOR_USER_CONFIRMED_FINAL_STATS_WITH_DAMAGE_ITEM_PROFILE = {
    "id": "user_confirmed_final_stats_level50_with_damage_item",
    "label": "User-confirmed final stats / Level 50 / supported damage item",
    "source": "user_input",
    "confidence": "higher_confidence_reference",
    "is_user_confirmed": True,
}

ADVISOR_DAMAGE_LIMITATIONS = [
    "This is not final battle damage.",
    "EV/IV/nature/final stats may be missing or defaulted.",
    "Only supported attacker-side damage item modifiers are applied when item_effects marks them as applied.",
    "Recoil, speed, survival, recovery, and other non-damage item effects are not connected unless a specific supported field says otherwise.",
    "Use as rough reference only.",
    "KO/OHKO/2HKO context, when present, is limited damage-roll context only and not final battle truth.",
]

ADVISOR_OPPONENT_DAMAGE_LIMITATIONS = [
    "This is not final battle damage.",
    "Opponent ability, EV/IV/nature, boosts, and final stats may be missing or defaulted.",
    "Only supported attacker-side damage item modifiers are applied when item_effects marks them as applied.",
    "Recoil, speed, survival, recovery, and other non-damage item effects are not connected unless a specific supported field says otherwise.",
    "Use as rough threat reference only.",
    "KO/OHKO/2HKO context, when present, is limited damage-roll context only and not final battle truth.",
]

ADVISOR_DAMAGE_ESTIMATE_STATUSES = {
    "available_with_default_assumptions",
    "unavailable_missing_move",
    "unavailable_no_selected_move",
    "unavailable_status_move",
    "unavailable_missing_power",
    "unavailable_missing_pokemon",
    "unavailable_missing_base_stats",
    "unavailable_missing_type",
    "unavailable_unsupported_category",
    "unavailable_engine_error",
}

ADVISOR_MISSING_FIELDS = [
    "final calculated stats",
    "EV/IV/nature",
    "full item effects",
    "selected ability certainty",
    "weather",
    "terrain",
    "stat boosts",
    "exact current HP integer",
    "opponent moves",
    "final KO/OHKO/2HKO truth",
    "turn order",
    "speed tie",
    "status duration",
    "Turn Engine state",
]
